
import React, { useState } from 'react';
import { Search, Hash, BookOpen, Loader2, Info } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { lookupLegalSection } from '../services/geminiService';

interface SectionLookupProps {
  isDarkMode: boolean;
}

const SectionLookup: React.FC<SectionLookupProps> = ({ isDarkMode }) => {
  const [query, setQuery] = useState('');
  const [result, setResult] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const handleSearch = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!query.trim() || loading) return;

    setLoading(true);
    try {
      const info = await lookupLegalSection(query);
      setResult(info);
    } catch (error) {
      setResult("Error searching for this section. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const trending = ["IPC Section 302", "BNS Section 103", "Article 21", "Section 498A", "POCSO Act"];

  return (
    <div className="max-w-4xl mx-auto py-8 px-4 animate-in fade-in duration-500">
      <div className="text-center mb-10">
        <h2 className={`text-3xl font-serif font-bold mb-3 flex items-center justify-center gap-2 transition-colors ${isDarkMode ? 'text-white' : 'text-slate-900'}`}>
          <Hash className="text-amber-500" />
          Section & Article Lookup
        </h2>
        <p className={`transition-colors ${isDarkMode ? 'text-slate-300' : 'text-slate-600'}`}>
          Search any specific section from IPC, BNS, CrPC, or the Constitution for detailed info.
        </p>
      </div>

      <div className={`rounded-2xl shadow-xl overflow-hidden mb-8 border transition-all ${isDarkMode ? 'bg-slate-900/50 border-slate-700' : 'bg-white border-slate-200'}`}>
        <div className="p-6 md:p-8">
          <form onSubmit={handleSearch} className="relative mb-6">
            <div className="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none">
              <Search className="text-slate-400" size={20} />
            </div>
            <input
              type="text"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder="Enter section (e.g., IPC 302, Article 32, Section 138 NI Act)..."
              className={`w-full pl-12 pr-32 py-4 rounded-xl border focus:ring-2 focus:ring-amber-500 focus:outline-none transition-all ${isDarkMode ? 'bg-slate-800 border-slate-700 text-white placeholder-slate-500' : 'bg-slate-50 border-slate-200 text-slate-900'}`}
            />
            <button
              type="submit"
              disabled={loading || !query.trim()}
              className="absolute right-2 top-2 bottom-2 px-6 bg-amber-500 hover:bg-amber-600 text-slate-900 font-bold rounded-lg transition disabled:opacity-50"
            >
              {loading ? <Loader2 className="animate-spin" size={20} /> : 'Search'}
            </button>
          </form>

          <div className="flex flex-wrap gap-2 items-center">
            <span className={`text-xs font-bold uppercase tracking-wider ${isDarkMode ? 'text-slate-500' : 'text-slate-400'}`}>Popular:</span>
            {trending.map(t => (
              <button
                key={t}
                onClick={() => {
                  setQuery(t);
                  // Trigger search logic could go here or user clicks search
                }}
                className={`text-xs px-3 py-1.5 rounded-full border transition-colors ${isDarkMode ? 'bg-slate-800 border-slate-700 text-slate-300 hover:text-amber-400' : 'bg-slate-100 border-slate-200 text-slate-600 hover:text-amber-600'}`}
              >
                {t}
              </button>
            ))}
          </div>
        </div>
      </div>

      {result && (
        <div className={`rounded-2xl shadow-2xl border overflow-hidden animate-in slide-in-from-bottom-4 duration-500 ${isDarkMode ? 'bg-slate-900 border-slate-700' : 'bg-white border-slate-200'}`}>
          <div className="bg-amber-500/10 px-6 py-4 border-b border-amber-500/20 flex items-center gap-3">
            <BookOpen className="text-amber-500" size={20} />
            <h3 className="font-bold text-amber-500 uppercase tracking-widest text-sm">Legal Breakdown</h3>
          </div>
          <div className={`p-8 markdown-content ${isDarkMode ? 'text-slate-200' : 'text-slate-800'}`}>
             <ReactMarkdown remarkPlugins={[remarkGfm]}>
                {result}
             </ReactMarkdown>
          </div>
          <div className="bg-slate-50 px-8 py-4 flex items-center gap-2 border-t border-slate-100">
            <Info size={14} className="text-slate-400" />
            <span className="text-xs text-slate-400 font-medium italic">Data generated by AI. Always verify with official gazettes.</span>
          </div>
        </div>
      )}
    </div>
  );
};

export default SectionLookup;
